server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devconnect_auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

jwt:
  secret: mysupersecretkeythatislongenough123456
  expiration: 3600000

