server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devconnect_auth
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

jwt:
  secret: mysupersecretkeythatislongenough123456
  expiration: 3600000
