services:
  mysql-auth:
    image: mysql:8
    container_name: mysql-auth
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devconnect_auth
    ports:
      - "3307:3306"
    volumes:
      - mysql-auth-data:/var/lib/mysql

  mysql-user:
    image: mysql:8
    container_name: mysql-user
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devconnect_user
    ports:
      - "3308:3306"
    volumes:
      - mysql-user-data:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8081:8081"
    depends_on:
      - mysql-auth
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-auth:3306/devconnect_auth
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAPSERVERS: kafka:9092
      JWT_SECRET: mysupersecretkeythatislongenough123456
      JWT_EXPIRATION: 3600000
    command: ["./wait-for-it.sh", "mysql-auth:3306", "--", "java", "-jar", "/app/auth-service.jar"]

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8082:8082"
    depends_on:
      - mysql-user
      - kafka
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-user:3306/devconnect_user
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    command: ["./wait-for-it.sh", "mysql-user:3306", "--", "java", "-jar", "/app/user-service.jar"]

volumes:
  mysql-auth-data:
  mysql-user-data:
